spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: vovasamb999@gmail.com
    password: jgicfgwgcsdqhnmd
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
      mail:
        smtp:
          starttls:
            enable: true

app:
  notificationEmail: vovasamb@yandex.ru
